kara_mul_comb: 
	$(MAKE) -C test_kara_mul/combinational/
#kara_mul_fp: 
#	$(MAKE) -C test_kara_mul/full_pipelined/

kara_mul_low_comb: 
	$(MAKE) -C test_kara_mul_low/combinational/
#kara_mul_low_fp: 
#	$(MAKE) -C test_kara_mul_low/full_pipelined/

kara_mul_high_comb: 
	$(MAKE) -C test_kara_mul_high/combinational/
#kara_mul_high_fp: 
#	$(MAKE) -C test_kara_mul_high/full_pipelined/

mod_add_comb:
	$(MAKE) -C test_mod_add/combinational/
#mod_add_fp:
#	$(MAKE) -C test_mod_add/full_pipelined/

mod_mul_comb:
	$(MAKE) -C test_mod_mul/combinational/
#mod_add_fp:
#	$(MAKE) -C test_mod_mul/full_pipelined/

point_adder_comb:
	$(MAKE) -C test_point_adder/combinational/
#point_adder_fp:
#	$(MAKE) -C test_point_adder/full_pipelined/
